#!/usr/bin/env ruby

def go_direction pool, start, i, j, turn, to_change
    count, go = 0, [0, 0]
    go[0] = start[0] + i
    go[1] = start[1] + j

    while pool[go] != 0 and pool[go] != turn
        go[0] += i
        go[1] += j
        count += 1
    end

    return 0 if pool[go] == 0
    return count if not to_change

    go[0] -= i
    go[1] -= j

    while pool[go] != pool[start]
        pool[go] = turn
        go[0] -= i
        go[1] -= j
    end

    return count
end

class Hash
    def valid s, turn, to_change
        return (not self.has_moves(turn)) if s == "Skip"
        return false if s.length != 2
        return false if !('a'..'h').include?(s[0])
        return false if !('1'..'8').include?(s[1])
        m = [s[0].ord - 'a'.ord + 1, s[1].to_i]
        return false if self[m] != 0
        self[m] = turn if to_change
        
        sum = 0
        [-1, 0, 1].each do |i|
            [-1, 0, 1].each do |j|
                sum += go_direction(self, m, i, j, turn, to_change) if i != 0 || j != 0
            end
        end
        return sum > 0
    end

    def has_moves turn
        ('a'..'h').each do |a|
            ('1'..'8').each do |b|
                return true if self.valid(a + b, turn, false)
            end
        end
        false
    end

    def winner turn
        return nil if has_moves(turn)
        return nil if has_moves(3 - turn)

        return [0, 1, 2][self.score(1) <=> self.score(2)]
    end

    def score turn
        sc = 0
        (1..8).each do |i|
            (1..8).each do |j|
                sc += 1 if self[[i, j]] == turn
            end
        end
        return sc
    end

    def formprint
        w = {1=>'a', 2=>'b', 3=>'c', 4=>'d', 5=>'e', 6=>'f', 7=>'g', 8=>'h'}
        STDERR.puts " 12345678"
        (1..8).each do |i|
            STDERR.print w[i]
            (1..8).each do |j|
                STDERR.print "*" if self[[i, j]] == 1
                STDERR.print "&" if self[[i, j]] == 2
                STDERR.print "_" if self[[i, j]] == 0
            end
            STDERR.puts
        end
        sleep 0.5
    end
end

def final winner, score
    main_score = ["1:1", "2:0", "0:2"][score[1] <=> score[2]]
    second_score = score[1].to_s + ':' + score[2].to_s
    return main_score + " (" + second_score + ")"
end

pool = Hash.new(0)
STDOUT.sync = true
turn, winner, score = 1, nil, []

pool[[4, 4]] = 2
pool[[5, 5]] = 2
pool[[4, 5]] = 1
pool[[5, 4]] = 1

while true 
#    pool.formprint
    case (s = gets.chomp)[0]
    when 'i' then
        winner ||= 3 - turn
        score[turn] = -1
        score[winner] = pool.score(winner)
        print winner.to_s + final(winner, score) + "\n"
    when 'f' then
        winner ||= pool.winner(turn)
        score[1] ||= pool.score(1)
        score[2] ||= pool.score(2)
        print winner.to_s + final(winner, score) + "\n"
    when 'c' then
        gets
        puts "OK"
    else
        s = s[1..-1]
        if not winner and pool.valid(s, turn, true)
            if winner ||= pool.winner(turn)
                score[1] = pool.score(1)
                score[2] = pool.score(2)
                print winner.to_s + final(winner, score) + "\n"
            else
                print " " + s + "\n"
                turn = 3 - turn
            end
        else
            if not winner
                winner = 3 - turn
                score[turn] = -1
                score[winner] = pool.score(winner)
                print "i" + final(winner, score) + "\n"
            else
                score[1] ||= pool.score(1)
                score[2] ||= pool.score(2)
                print winner.to_s + final(winner, score) + "\n"
            end
        end
    end
end
